### ISSUE TITLE
Don't run weston as a root user

### ISSUE THREAD

**Issue by zoltan-ongithub** [96boards/meta-96boards#85]
We should not run weston under the root user. To fix this issue, we need to create a separate weston group. Make sure that the new group can access the input devices and DRM driver.

**Comment by fboudra** [comment]
@mrchapp can you check that as part of your weston fixes/bugs? thanks.

**Comment by mrchapp** [comment]
It seems possible using the video group and changing /dev/mali (at least on Hikey) to make it accessible to that group. So, basically:
1) add user linaro to group video,
2) add udev rule to have /dev/mali as 0660 and set group to video,
3) change systemd unit to set User=linaro,
4) redirect log somehow so that /var/log/weston.log is writable.

That works with `systemctl start weston` but not directly on boot. Will keep you posted.

**Comment by fboudra** [comment]
3. why?
4. writable by who?

The point is weston needs to be run by a dedicated system account. If such account doesn't exist, we should create one for this purpose. I suspect general purpose distro have already something, have a look to latest debian/fedora. Except if we have a dm.

It reminds me a prior discussion and I think @koenkooi wanted to go the systemd way and needed to make   a proposal on how it will/should work? @ndechesne do you remember?

**Comment by koenkooi** [comment]
Making it a user session should give it a seat and access to input and video.

**Comment by ndechesne** [comment]
+1 for making proper user session (both for weston and for our x11 desktop image). since we are making a 'reference image', it's better this way..

**Comment by fboudra** [comment]
@mrchapp Any progress?

**Comment by mrchapp** [comment]
Latest Fedora has a display manager, but that calls Xwayland... I have tried a few display managers and they are all rely on X and have very tightly coupled dependencies on it (GDM, LightDM, nodm, cdm) and making those work without X looks daunting. I'm currently trying TLM [Tiny Login Manager], and this one looks better.

As for the systemd way, I'm all ears. Currently it does create a session and it's correctly listed for user linaro with loginctl, with the correct devices under the right seat.

Following up on the questions,
3) user=linaro because it was the only user that existed and the subject of this issue is to use a non-root user.
4) Writable by user linaro. I have seen $XDG_RUNTIME_DIR/my.log, but I feel that a little too disposable for a log file.

**Comment by mrchapp** [comment]
Koen mentioned this article:
  https://wiki.archlinux.org/index.php/Systemd/User

Following that through, it seems that a display manager is not needed at all and that the systemd service can run with the user directly. Please have a look at these commits and let me know if that looks like an agreeable approach:
  https://github.com/mrchapp/meta-96boards/commits/weston-run-user

That still needs adding the user linaro to group video in meta-rpb/recipes-samples/images/rpb-weston-image.bb
  -usermod -a -G weston-launch linaro; \
  +usermod -a -G weston-launch,video linaro; \

Worksforme, tested on Hikey Morty.

**Comment by ndechesne** [comment]
nice.. any chance you can look at how to do the same with Xserver? right now in the -desktop image we are starting X as root, and i would like to see user session instead..

**Comment by koenkooi** [comment]
Looks good to me as well

**Comment by fboudra** [comment]
agreed with the approach. The udev rules is more or less what we use on Debian.

Please submit the pull request for a proper review. Thanks!

**Comment by fboudra** [comment]
https://github.com/96boards/meta-96boards/commit/66aac8405da014b1851fffdb9a638df7ac2dce60
https://github.com/96boards/meta-rpb/commit/3f61371e7db090abf3dbb2a2fb626c57306bdc1d

**Comment by fboudra** [comment]
https://github.com/96boards/meta-96boards/commit/253c153745bbcaa002f380cd4446629f92cc785b
https://github.com/96boards/meta-96boards/commit/8a2a30fc853f123a717300bde32ebb38e1d3391c
